name: memo4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  connectivity_plus: ^4.0.1
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.4
  pdf: ^3.11.1
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10
  another_flushbar: ^1.12.30
  firebase_messaging: ^15.1.5
  fl_chart: ^0.69.2
  printing: ^5.12.0
  flutter_local_notifications: ^18.0.1
  syncfusion_flutter_charts: ^27.2.5
  device_info_plus: ^10.0.0
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
